module.exports = {
  'accessToken.button.default': `Save API Token`,
  'accessToken.button.submitting': `Please wait`,
  'accessToken.name': `Name`,
  'accessToken.role': `Role associated with this API token`,
  'accessToken.token': `API Token`,
  'admin.accessToken.create.failure': `Couldn't create API token!`,
  'admin.accessToken.create.success': `API token created successfully!`,
  'admin.accessToken.destroy.failure': `Couldn't delete API token!`,
  'admin.accessToken.destroy.success': `API token deleted successfully!`,
  'admin.accessToken.regenerateToken.failure': `Couldn't update API token!`,
  'admin.accessToken.regenerateToken.success': `API token regenerated successfully!`,
  'admin.accessToken.update.failure': `Couldn't update API token!`,
  'admin.accessToken.update.success': `API token updated successfully!`,
  'admin.webhook.create.failure': `Couldn't create webhook!`,
  'admin.webhook.create.success': `Webhook created successfully!`,
  'admin.webhook.destroy.failure': `Couldn't delete webhook!`,
  'admin.webhook.destroy.success': `Webhook deleted successfully!`,
  'admin.webhook.update.success': `Webhook updated successfully!`,
  'admin.webhook.update.failure': `Couldn't update webhook`,
  'admin.webhook.noWebhooks.description': `Create your first webhook!`,
  'admin.webhook.noWebhooks.title': `Still no webhooks`,
  'admin.deploymentEnvironments.noEnvs.title': `Still no deployment environments`,
  'admin.deploymentEnvironments.noEnvs.description': `Connect this project with an external Continuous Deployment service like Netlify to use DatoCMS with static websites!`,
  'form.newWebhookForm.title': `Create a new webhook`,
  'form.editWebhookForm.title': `Edit webhook`,
  'form.editWebhookForm.delete': `Delete`,
  'form.webhook.httpSettings': `HTTP Settings`,
  'form.webhook.basicAuth': `HTTP basic auth`,
  'form.webhook.customHeaders': `Custom headers`,
  'form.webhook.triggers': `Triggers`,
  'form.webhook.trigger.add': `Add new trigger`,
  'form.webhook.webhookTriggers': `Webhook triggers`,
  'form.webhook.body': `HTTP Body`,
  'form.webhook.name': `Name`,
  'form.webhook.headers': `Custom headers`,
  'form.webhook.events.label': `Webhook triggers`,
  'form.webhook.url': `URL`,
  'form.webhook.httpBasic': `HTTP basic auth`,
  'form.webhook.httpBasicUser': `User`,
  'form.webhook.httpBasicPassword': `Password`,
  'form.webhook.button.default': `Submit`,
  'form.webhook.entityOptions': `Entity`,
  'form.webhook.eventTypes': `Events`,
  'form.webhook.entityTypeIds.item_type': `Model IDs (separated by commas)`,
  'form.webhook.entityTypeIds.item': `Record IDs (separated by commas)`,
  'form.webhook.entityTypeIds.deployment_environment': `Deployment environment IDs (separated by commas)`,
  'form.webhook.entityTypeIds.placeholder': `123, 33`,
  'form.webhook.ids': `Ids`,
  'form.webhook.filter': `Filter`,
  'form.webhook.custom_payload': `Send a custom payload?`,
  'form.webhook.custom_payload.label': `Payload template`,
  'form.webhook.custom_payload.hint': `Write here your custom payload. You can make it dynamic using <a href="http://mustache.github.io/mustache.5.html">Mustache</a> variables.`,
  'form.webhook.custom_payload.docs': `Learn more in our docs`,
  'admin.deploymentLogs.abort': `Abort and mark as failed`,
  'admin.deploymentLogs.noEvents.description': `Please request a new publication of the website to see this page filled with a log of the latest webhook events generated`,
  'admin.deploymentLogs.noEvents.title': `No events recorded yet!`,
  'admin.deploymentLogs.title': `Deployment logs`,
  'admin.deploymentSettings.ready': `Ready to connect DatoCMS with your Continuous Deployment?`,
  'admin.integration.howTo': `How to integrate DatoCMS with your site`,
  'admin.integration.ready': `Ready to start the integration?`,
  'admin.integration.select': `Please select your static site generator:`,
  'admin.integration.success.title': `You did it!`,
  'admin.integration.waiting': `Waiting for the completion of the steps...`,
  'admin.item.noFields.button': `Edit the model`,
  'admin.item.noFields.description': `This model currently has no fields: to start creating some records of this type, please head over to the Admin Area > Models section and add some!`,
  'admin.item.noFields.title': `Add some fields!`,
  'admin.itemType.create.failure': `Couldn't create the model!`,
  'admin.itemType.create.success': `Model successfully created`,
  'admin.itemType.createField.failure': `Couldn't add field!`,
  'admin.itemType.createField.success': `Field successfully added`,
  'admin.itemType.destroy.failure': `Couldn't remove the model!`,
  'admin.itemType.destroy.success': `Model successfully removed`,
  'admin.itemType.destroyField.failure': `Couldn't remove the field!`,
  'admin.itemType.destroyField.neededBySlugField': `Field cannot be destroyed as it's used as reference for the \"{slugField}\" slug field!`,
  'admin.itemType.destroyField.success': `Field successfully removed`,
  'admin.itemType.duplicateItemType.failure': `Couldn't duplicate the model`,
  'admin.itemType.duplicateItemType.success': `Model successfully duplicated!`,
  'admin.itemType.noFields.description': `What kind of information needs to be editable for a record of type \"{name}\"? A title? Some textual content? Maybe an image? Define the different fields we should present to editors of this site.`,
  'admin.itemType.noFields.title': `Add some fields to this model!`,
  'admin.itemType.reorderField.failure': `Couldn't reorder fields!`,
  'admin.itemType.reorderField.success': `Fields successfully reordered`,
  'admin.itemType.update.failure': `Couldn't update the model!`,
  'admin.itemType.update.success': `Model successfully updated`,
  'admin.itemType.updateField.failure': `Couldn't update the field!`,
  'admin.itemType.updateField.success': `Field successfully updated`,
  'admin.itemTypes.noItemTypes.description': `Articles, products, categories, team members... what kind of content is your website made of? Create a new \"model\" for every type of object that you want to make editable!`,
  'admin.itemTypes.noItemTypes.docs': `Read more in our docs`,
  'admin.itemTypes.noItemTypes.title': `Welcome! Let's give a shape to this backend!`,
  'admin.menuItem.create.failure': `Couldn't create the menu item!`,
  'admin.menuItem.create.success': `Menu item successfully created`,
  'admin.menuItem.destroy.failure': `Couldn't remove the menu item!`,
  'admin.menuItem.destroy.success': `Menu item successfully removed`,
  'admin.menuItem.reorder.failure': `Couldn't reorder the menu items!`,
  'admin.menuItem.reorder.success': `Menu items successfully reordered`,
  'admin.menuItem.update.failure': `Couldn't update the menu item!`,
  'admin.menuItem.update.success': `Menu item successfully updated`,
  'admin.modularBlock.add.failure': `Couldn't add modular block!`,
  'admin.modularBlock.add.success': `Modular block added successfully!`,
  'admin.modularBlock.create.failure': `Couldn't create modular block!`,
  'admin.modularBlock.create.success': `Modular block created successfully!`,
  'admin.modularBlock.noFields.description': `What kind of information needs to be editable for a block of type \"{name}\"? A title? Some textual content? Maybe an image? Define the different fields we should present to editors of this site.`,
  'admin.modularBlock.noFields.title': `Add some fields to this block!`,
  'admin.modularBlock.removed.failure': `Couldn't remove modular block!`,
  'admin.modularBlock.removed.success': `Modular block removed successfully!`,
  'admin.modularBlock.update.failure': `Couldn't update modular block!`,
  'admin.modularBlock.update.success': `Modular block updated successfully!`,
  'admin.site.update.failure': `Couldn't update site settings!`,
  'admin.site.update.success': `Settings successfully updated`,
  'admin.version.restore.failure': `Couldn't restore revision!`,
  'admin.version.restore.success': `Previous revision successfully restored!`,
  'adminArea.splitPane.apiTokens': `API tokens`,
  'adminArea.splitPane.plugins': `Plugins`,
  'adminArea.splitPane.deploymentLogs': `Activity log`,
  'adminArea.splitPane.deploymentSettings': `Environments`,
  'adminArea.splitPane.itemTypes': `Models`,
  'adminArea.splitPane.manageEditors': `Collaborators`,
  'adminArea.splitPane.manageWebhooks': `Webhooks`,
  'adminArea.splitPane.webhookCalls': `Activity log`,
  'adminArea.splitPane.manageRoles': `Roles`,
  'adminArea.splitPane.menuSettings': `Navigation bar`,
  'adminArea.splitPane.siteSettings': `Settings`,
  'adminArea.splitPane.ssgIntegration': `Static generator settings`,
  'adminArea.splitPane.usage': `Usage and plan limits`,
  'adminArea.splitPane.permissions': `Permissions`,
  'accessToken.permissions': `Permissions`,
  'appareance.stringAppareance.plain': `Normal string`,
  'appareance.stringAppareance.title': `Title (this field represents the record title)`,
  'editor.wysiwyg': `HTML editor`,
  'editor.markdown': `Markdown editor`,
  'editor.textarea': `Simple textarea`,
  'editor.link_select': `Compact view`,
  'editor.link_embed': `Expanded view`,
  'editor.links_select': `Compact view`,
  'editor.links_embed': `Expanded view`,
  'editor.changeRole': `Change role`,
  'editor.remove': `Remove from project`,
  'editor.add': `Add collaborator`,
  'editor.active': `Active`,
  'editor.invite.new': `Invite new collaborator`,
  'editor.invited': `Invited`,
  'editor.table.user': `User`,
  'editor.table.status': `Status`,
  'editor.table.2fa': `2fa`,
  'editor.table.role': `Role`,
  'singleLine.heading': `Show as heading?`,
  'fieldForm.appeareance.editor': `Field editor`,
  'fieldForm.appeareance.editor.hint': `Choose how this field should be displayed`,
  'belongsToInput.create.single': `New {itemType}`,
  'belongsToInput.replace.single': `New {itemType}`,
  'belongsToInput.create.multiple': `Create new...`,
  'belongsToInput.replace.multiple': `Create new...`,
  'button.default': `Send`,
  'button.submitting': `Please wait`,
  'button.uploading': `Waiting for image upload`,
  'circle_ci.apiToken': `Step 1: Generate API Token`,
  'circle_ci.apiTokenDescription': `From your CircleCI account generate an account API Token and paste it here:`,
  'circle_ci.button.default': `Save CircleCI settings`,
  'circle_ci.config': `Step 3: Edit config file`,
  'circle_ci.configDescription1': `Add two additional run steps to your .circleci/config.yml file:`,
  'circle_ci.editorname': `Editorname`,
  'circle_ci.project': `Step 2: Specify the project name`,
  'circle_ci.projectDescription': `Find the name of the CircleCI project and paste the project name here`,
  'circle_ci.projectDescription3': `Specify the Git branch you want to build`,
  'circle_ci.buildParameters': `Specify any custom environment variables you want to be available during the build`,
  'circle_ci.revision': `Branch to build`,
  'circle_ci.token': `API token`,
  'circle_ci.project.placeholder': `username/project`,
  'circle_ci.branch.placeholder': `master`,
  'circle_ci.vcs': `Specify the version control system type your project uses`,
  'clipboard.copied': `Copied!`,
  'clipboard.copy': `Copy`,
  'color.enableAlpha': `Let editors control the alpha channel?`,
  'color.presetColors': `Preset colors`,
  'color.presetColors.hint': `This is useful if you want to present your editors a set of reference colors. Delimit colors with a comma.`,
  'color.presetColors.placeholder': `#FF0000, #00FF00, #0000FF`,
  'completeRegistration.password': `Welcome! Please choose a password for your account:`,
  'completeRegistration.passwordHint': `The password should be at least 8 characters long, have a lowercase letter, an uppercase letter and a number`,
  'completeRegistration.button.default': `Set password and sign in`,
  'custom.button.default': `Save settings`,
  'custom.trigger': `Step 1: Trigger URL`,
  'custom.triggerDescription': `DatoCMS will send a POST request to the specified endpoint on every publish request.`,
  'custom.triggerUrl': `Specify the URL of the trigger endpoint:`,
  'custom.triggerUrlPlaceholder': `https://api.yourapp.com/request_build`,
  'custom.webhook': `Step 2: Status notifications`,
  'custom.webhookDescription': `After each build, make sure to notify DatoCMS with the status of the publishing operation with a POST request to the following URL:`,
  'custom.payload': `Specify the JSON payload to send with the request`,
  'custom.headers': `Custom headers`,
  'dashboard.description': `Please, select the content you would like to edit in the left sidebar`,
  'dashboard.title': `Hello {name}!`,
  'dateTimeInput.insertDate': `Insert date`,
  'dateTimeInput.insertDateTime': `Insert date and time`,
  'dateTimeInput.time': 'Time',
  'deployEvent.details.command': `Request we performed`,
  'deployEvent.details.pages': `Indexed pages`,
  'deployEvent.details.pages_count': `Number of pages indexed`,
  'deployEvent.details.reason': `Reason`,
  'deployEvent.details.requestBody': `Request Body`,
  'deployEvent.details.requestHeaders': `Request Headers`,
  'deployEvent.details.responseBody': `Response Body`,
  'deployEvent.details.responseHeaders': `Response Headers`,
  'deployEvent.details.responseStatusCode': `Response Status Code`,
  'deployEvent.details.timestamp': `Event Timestamp`,
  'deployEvent.detailsTitle': `Event details`,
  'deployEvent.showDetails': `Show details`,
  'deployEvent.type.in_progress': `Deploy in progress`,
  'deployEvent.type.request': `Requested a new build`,
  'deployEvent.type.request_aborted': `Build aborted`,
  'deployEvent.type.request_failed': `Failed to request a new build`,
  'deployEvent.type.request_unprocessable': `Received an invalid webhook`,
  'deployEvent.type.response_failure': `Build failed`,
  'deployEvent.type.response_success': `Build completed with success`,
  'deployEvent.type.response_timeout': `Build took too long to complete`,
  'deployEvent.type.scrape_complete': `Site spidering completed with success`,
  'deployEvent.type.scrape_failure': `Site spidering failed`,
  'deployEvent.type.scrape_in_progress': `Spidering in progress`,
  'deployEvent.type.scrape_request': `Started site spidering`,
  'deployPanel.clean.label': `Published`,
  'deployPanel.createItemTypes.button': `Read more in our docs!`,
  'deployPanel.createItemTypes.description': `DatoCMS can be seen as a client-friendly interface over a database, so the first step is to build the actual schema upon which users will generate the actual website content.`,
  'deployPanel.createItemTypes.label': `Next step: define the schema`,
  'deployPanel.createItemTypes.title': `Let's give a shape to this backend!`,
  'deployPanel.createItems.button': `Switch to the Content tab`,
  'deployPanel.createItems.description': `Now that we have some models, you can already start generating content for your website!`,
  'deployPanel.createItems.label': `Next step: write some content`,
  'deployPanel.createItems.title': `You can start writing some content!`,
  'deployPanel.failure.admin.description': `The latest deploy had some problems, please {link} to find more about the cause.`,
  'deployPanel.failure.admin.link': `take a look at the logs`,
  'deployPanel.failure.admin.title': `Ouch, the latest deployment process failed!`,
  'deployPanel.failure.button': `Try building again`,
  'deployPanel.failure.editor.description': `Please contact your website admins to know what happened... in the meantime, you can try repeating the build process!`,
  'deployPanel.failure.editor.title': `Damn, we could not build the website!`,
  'deployPanel.failure.label': `Publication failed`,
  'deployPanel.failure.user.description': `The latest deploy had some problems, please contact the site administrator.`,
  'deployPanel.failure.user.title': `Ouch, the website build process didn't go well :(`,
  'deployPanel.neverDeployed.button': `Build now`,
  'deployPanel.pending.description': `Please wait for the completion of the publication process (it will take approximately 30 seconds)`,
  'deployPanel.pending.label': `Publication in progress`,
  'deployPanel.pending.title': `We are publishing a new version of the website!`,
  'deployPanel.toConfigure.button': `Open settings`,
  'deployPanel.touched.button': `Build now`,
  'deployPanel.touched.description': `The updated content won't be visible online until you explicitly decide to request a new publication.`,
  'deployPanel.touched.label': `Build site`,
  'deployPanel.touched.title': `You made some changes to the content of the website!`,
  'deploySettingsInput.title': `Configure {activeAdapter}`,
  'deploymentEnvironments.title': `Deployment status`,
  'deploymentEnvironments.options': `Options`,
  'deploymentEnvironments.buildMethod': `Build method`,
  'deploymentEnvironments.production': `Production`,
  'deploymentEnvironments.staging': `Staging`,
  'deploymentEnvironments.status.clean': `Deployed and up to date`,
  'deploymentEnvironments.status.fail': `Last deploy failed.`,
  'deploymentEnvironments.status.log': `{link} to find out the cause.`,
  'deploymentEnvironments.status.log.link': `Inspect the logs`,
  'deploymentEnvironments.status.neverDeployed': `Never deployed`,
  'deploymentEnvironments.status.pending': `Build in progress...`,
  'deploymentEnvironments.status.toConfigure': `Environment not configured`,
  'deploymentEnvironments.status.touched': `Deployed {date}, some changes not published`,
  'deploymentSettings.title': `Hosting and automated deploy setup`,
  'editItem.title': `Edit {name}`,
  'editor.button.default': `Send invitation via email`,
  'editor.editor.create.failure': `Couldn't invite collaborator!`,
  'editor.editor.create.success': `Invitation successfully sent!`,
  'editor.editor.destroy.failure': `Couldn't remove user!`,
  'editor.editor.destroy.success': `User successfully removed`,
  'editor.editor.update.failure': `Couldn't update user settings!`,
  'editor.editor.update.success': `User successfully updated`,
  'editor.editors.noEditors.description': `You still have not shared your project with anyone! Invite your team and start collaborating!`,
  'editor.editors.noEditors.title': `😔 It feels a little lonely here...`,
  'editor.email': `Email`,
  'editor.firstName': `First name`,
  'editor.isAdmin': `Admin?`,

  'editor.item.create.failure': `Couldn't create the record!`,
  'editor.item.create.success': `Record successfully created`,
  'editor.item.destroy.failure': `Cannot delete the record, as it's required by other records:`,
  'editor.item.destroy.success': `Record successfully removed`,
  'editor.item.duplicate.failure': `Couldn't duplicate record!`,
  'editor.item.duplicate.success': `Record has been successfully duplicated!`,
  'editor.item.noItems.description': `Start filling it with new \"{name}\" records right away!`,
  'editor.item.noItems.title': `This collection is empty`,
  'editor.item.noItems.button': `Create a new record`,
  'editor.item.publish.failure': `Couldn't publish the record!`,
  'editor.item.publish.success': `Record successfully published!`,
  'editor.item.scheduledPublish.success': `Record successfully scheduled for publication!`,
  'editor.item.scheduledPublish.failure': `Couldn't schedule the record for publication!`,
  'editor.item.destroyScheduledPublication.success': `Scheduled publication successfully cancelled!`,
  'editor.item.destroyScheduledPublication.failure': `Couldn't cancel scheduled publication!`,
  'editor.item.reorder.failure': `Couldn't reorder the records!`,
  'editor.item.reorder.success': `Records successfully reordered`,
  'editor.item.unpublish.failure': `Couldn't unpublish the record!`,
  'editor.item.publish.failure.UNPUBLISHED_LINK': `Couldn't publish the record, as it links the following unpublished records:`,
  'editor.item.publish.failure.UNPUBLISHED_PARENT': `Couldn't publish the record, as the parent record is not published:`,
  'editor.item.unpublish.failure.LINKED_FROM_PUBLISHED_ITEMS': `Couldn't unpublish the record, as the following published records are linked to it:`,
  'editor.item.unpublish.failure.PUBLISHED_CHILDREN': `Couldn't unpublish the record, as the following children records are still published:`,
  'editor.item.unpublish.success': `Record successfully unpublished!`,
  'editor.item.update.failure': `Couldn't update the record!`,
  'editor.item.update.success': `Record successfully updated`,

  'editor.item.batch.delete.result': `{successful, plural, =0 {No record deleted} one {One record successfully deleted!} other {{successful} records successfully deleted!} }`,
  'editor.item.batch.publish.result': `{successful, plural, =0 {No record published} one {One record successfully published!} other {{successful} records successfully published!} }`,
  'editor.item.batch.unpublish.result': `{successful, plural, =0 {No record unpublished} one {One record successfully unpublished!} other {{successful} records successfully unpublished!} }`,
  'editor.item.batch.delete.failure': `Couldn't destroy the records!`,
  'editor.item.batch.publish.failure': `Couldn't publish the records!`,
  'editor.item.batch.unpublish.failure': `Couldn't unpublish the records!`,
  'editor.item.batch.limitReached': `Sorry, the maximimum records you can update at the same time is {limit}! Select a shorter list of records and retry.`,

  'editor.item.new': `New record`,
  'editor.lastName': `Last name`,
  'editor.password': `Password`,
  'editor.passwordHint': `Fill this field only if you want to change your current password, and remember that it should be at least 8 characters long, have a lowercase letter, an uppercase letter and a number`,
  'editor.role': `Role`,
  'editor.role.create.failure': `Couldn't create role!`,
  'editor.role.create.success': `New role created successfully!`,
  'editor.role.destroy.failure': `Couln't delete role!`,
  'editor.role.destroy.success': `Role deleted successfully!`,
  'editor.role.update.failure': `Couldn't update role!`,
  'editor.role.update.success': `Role updated successfully!`,
  'editor.site.update.failure': `Couldn't update site settings!`,
  'editor.site.update.success': `Settings successfully updated`,
  'editor.upload.batchDestroy.failure': `Couldn't delete the assets`,
  'editor.upload.batchDestroy.result': `{deleted, plural, =0 {No asset deleted} one {One asset} other {{deleted} assets} } deleted{inUse, plural, =0 {} one {, one asset not deleted as it's currently used} other {, {inUse} assets not deleted as they're currently used} }`,
  'editor.upload.create.failure': `Couldn't upload the file!`,
  'editor.upload.create.success': `File uploaded successfully!`,
  'editor.upload.destroy.failure': `Cannot delete the asset as it's currently used`,
  'editor.upload.destroy.failure.UPLOAD_IS_CURRENTLY_IN_USE': `Couldn't delete this asset, as it's currently used in the following records:`,
  'editor.upload.destroy.failure.UPLOADS_ARE_CURRENTLY_IN_USE': `Couldn't delete these assets:`,
  'editor.upload.destroy.failure.UPLOAD_NOT_PASSING_FIELD_VALIDATIONS': `Couldn't update this upload since the following records are failing to pass the validations:`,
  'editor.upload.destroy.success': `Asset deleted successfully!`,
  'editor.upload.update.failure': `Couldn't update the asset!`,
  'editor.upload.update.success': `Asset updated successfully!`,
  'editor.upload.update.replace': `Replace with a new asset...`,
  'embedsManyInput.add.single': `New {itemType}`,
  'embedsManyInput.add.multiple': `Create new...`,
  'embedsManyInput.edit': `Edit`,
  'embedsManyInput.modal.addTitle': `Add and assign {name}`,
  'embedsManyInput.modal.editTitle': `Edit and assign {name}`,
  'embedsManyInput.remove': `Remove`,
  'embedsManyInput.duplicate': `Duplicate`,
  'embedsManyInput.advancedSearch': `From library`,
  'field.addons': `Field add-ons`,
  'field.insertAddon': `Insert add-on`,
  'field.addon.defaultEditor': `Default editor`,
  'field.title.placeholder': `Title`,
  'field.apiKey': `Field ID`,
  'field.apiKey.placeholder': `title`,
  'field.apiKeyHint': `It is generated automatically based on the name and will appear in the API responses`,
  'field.appeareance': `Presentation mode`,
  'field.appeareanceHint': `Please choose the most appropriate type of input to present this field to site editors`,
  'field.button.default': `Save field`,
  'field.button.submitting': `Please wait`,
  'field.config': `Settings`,
  'field.convert': `Do you want to convert this field into a { field_type } field?`,
  'field.defaultValue': `Default Value`,
  'field.defaultValueHint': `The field will pre-filled with this value`,
  'field.defaultValuePlaceholder': `Please insert default value here`,
  'field.field_type': `Field type`,
  'field.hint': `Help text`,
  'field.hintHint': `This help text will show up below the field`,
  'field.hintPlaceholder': `Insert your text help here`,
  'field.label': `Name`,
  'field.labelHint': `The name to show to the editors`,
  'field.localized': `Enable localization on this field?`,
  'field.localizedHint': `Activate if you want this field to accept different values based on language`,
  'field.validators': `Validations`,
  'field.validatorsHint': `Specify any integrity rule to enforce on this field`,
  'richText.start_collapsed': `Show blocks as collapsed by default`,
  'fieldError.INVALID_FOR_CURRENT_PLAN': `Field not valid under the current plan`,
  'fieldError.FLOAT': `Field must be a floating point number`,
  'fieldError.GREATER_DATE_THAN': `Date must be greater than the previous one`,
  'fieldError.GREATER_THAN': `Field must be bigger than the previous one`,
  'fieldError.INTEGER': `Field must a positive integer`,
  'fieldError.INVALID_EMAIL': `Email not valid`,
  'fieldError.INVALID_FORMAT': `Format not valid`,
  'fieldError.API_KEY_FORMAT_INVALID': `Only letter, numbers and _ are allowed`,
  'fieldError.INVALID_URL': `Field must be a valid URL`,
  'fieldError.JSON': `Field must be valid JSON`,
  'fieldError.MAX_LENGTH': `Field cannot be more than { max_length } characters`,
  'fieldError.MIN_LENGTH': `Field must be at least { min_length } characters`,
  'fieldError.MIN_ARRAY_LENGTH': `Field must contain at least { min_length } values`,
  'fieldError.MIN_IMAGE_HEIGHT': `Image height must be at least { min_height }px`,
  'fieldError.MIN_IMAGE_WIDTH': `Image width must be at least { min_width }px`,
  'fieldError.MULTIPLE_INSTANCES_OF_SINGLETON': `Cannot convert to single instance as currently there is more than one record of this kind!`,
  'fieldError.REQUIRED_FIELD': `Field is required`,
  'fieldError.VALIDATION_REQUIRED_SEO_FIELDS': `{valorizedKeys, select,
      description { Field must specify SEO description }
      image { Field must specify sharing image }
      title { Field must specify SEO description }
      twitter_card { Field must specify SEO description }
      description_image { Field must specify SEO description and sharing image }
      description_title { Field must specify SEO title and description }
      description_twitter_card { Field must specify SEO description and type of Twitter card }
      image_title { Field must specify SEO title and sharing image }
      image_twitter_card { Field must specify sharing image and type of Twitter card }
      title_twitter_card { Field must specify SEO title and type of Twitter card }
      description_image_title { Field must specify SEO title, description and sharing image }
      description_image_twitter_card { Field must specify SEO description, sharing image and type of Twitter card }
      description_title_twitter_card { Field must specify SEO title, description and type of Twitter card }
      image_title_twitter_card { Field must specify SEO title, sharing image and type of Twitter card }
      description_image_title_twitter_card { Field must specify SEO title, description, sharing image and type of Twitter card }
  }`,
  'fieldError.SINGLETONS_CANNOT_BE_USED_AS_REFERENCE': `Cannot convert to single instance as this model is currently referenced in some Link, Links or Modular content field!`,
  'fieldError.SQUARE_IMAGE': `Image must be square`,
  'fieldError.VALIDATION_DATE_RANGE': `{ valorizedKeys, select, min { Date must be greater or equal than {min} } max { Date cannot be less or equal than {max} } max_min { Date must be between {min} and {max} } }`,
  'fieldError.VALIDATION_DATE_TIME_RANGE': `{ valorizedKeys, select, min { Date must be greater or equal than {min} } max { Date cannot be less or equal than {max} } max_min { Date must be between {min} and {max} } }`,
  'fieldError.VALIDATION_ENUM': `Field must contain one of the allowed values: { values }`,
  'fieldError.VALIDATION_MUSTACHE': `Field must be a valid Mustache template`,

  'fieldError.VALIDATION_EXTENSION': `{ valorizedKeys, select, predefined_list { Field must contain files of type { predefined_list } } extensions { Field must contain one of the allowed values: { extensions } } }`,
  'fieldError.VALIDATION_FILE_SIZE': `{ valorizedKeys, select,
    min_unit_min_value { File must be at least {min_value}{min_unit} }
    max_unit_max_value { File cannot exceed {max_value}{max_unit} }
    max_unit_max_value_min_unit_min_value { File size must be between {min_value}{min_unit} and {max_value}{max_unit} }
  }`,
  'fieldError.VALIDATION_IMAGE_DIMENSIONS': `{ valorizedKeys, select,
    height_min_value_width_min_value { Image must be at least {width_min_value}x{height_min_value}px }
    height_max_value_width_max_value { Image cannot exceed {width_max_value}x{height_max_value}px }
    height_max_value_height_min_value_width_max_value_width_min_value { Image dimensions must be between {width_min_value}x{height_min_value}px and {width_max_value}x{height_max_value}px }
  }`,

  'fieldError.VALIDATION_FORMAT': `{ valorizedKeys, select, custom_pattern { Field must respect a specific format } predefined_pattern { Field must be a valid { predefined_pattern, select, email { email address} url { URL } } } }`,
  'fieldError.VALIDATION_INVALID': `Field is invalid`,
  'fieldError.VALIDATION_JSON': `Field must be valid JSON`,
  'fieldError.VALIDATION_LENGTH': `{ valorizedKeys, select,
    min { Field must be at least {min} characters }
    max { Field cannot be more than {max} characters }
    max_min { Field length must be between {min} and {max} characters }
    eq { Field must be {eq} characters }
  }`,
  'fieldError.VALIDATION_NUMBER_RANGE': `{ valorizedKeys, select,
    min { Field value must be greater or equal than {min} }
    max { Field value cannot be less or equal than {max} }
    max_min { Field value must be between {min} and {max} }
  }`,
  'fieldError.VALIDATION_PLURAL': `The API identifier must expressed in singular form (ie. article, not articles)`,
  'fieldError.VALIDATION_REQUIRED': `Field is required`,
  'fieldError.VALIDATION_RESERVED': `This specified value is reserved and cannot be used`,
  'fieldError.VALIDATION_SIZE': `{ valorizedKeys, select,
    min { There must be at least {min} items }
    min_multiple_of { Insert at least {min} items in multiple of {multiple_of}}
    max { It is not possible to add more than {max} items }
    max_multiple_of { Insert no more than {max} items and in multiple of {multiple_of}}
    max_min { There must be a number of items between {min} and {max}}
    max_min_multiple_of { Insert between {min} and {max} items in multiple of {multiple_of}}
    eq { Number of items must be exactly {eq} } }`,
  'fieldError.VALIDATION_UNIQUE': `Field must contain an unique value`,
  'fieldError.VALIDATION_UNIQUENESS': `Field must contain an unique value`,
  'fieldError.VALIDATION_ITEMS_ITEM_TYPE': `Field cannot contain records of the provided model`,
  'fieldError.WEAK_PASSWORD': `The password must be at least 8 characters long, have a lowercase letter, an uppercase letter and a number`,
  'fieldForm.tab.basic': `Settings`,
  'fieldForm.tab.defaultValue': `Default value`,
  'fieldForm.tab.presentation': `Presentation`,
  'fieldForm.tab.validations': `Validations`,
  'fieldGroup.boolean.description': `Yes or no, 1 or 0, true or false`,
  'fieldGroup.boolean.title': `Boolean`,
  'fieldGroup.color.description': `RGB/Hex color, with or without alpha`,
  'fieldGroup.color.title': `Color`,
  'fieldGroup.datetime.description': `Event date, opening hours`,
  'fieldGroup.datetime.title': `Date and time`,
  'fieldGroup.json.description': `Custom metadata for your models`,
  'fieldGroup.json.title': `JSON`,
  'fieldGroup.location.description': `Coordinates: latitude and longitude`,
  'fieldGroup.location.title': `Location`,
  'fieldGroup.media.description': `Images, videos, PDFs and other files`,
  'fieldGroup.media.title': `Media`,
  'fieldGroup.number.description': `ID, order number, rating, quantity`,
  'fieldGroup.number.title': `Number`,
  'fieldGroup.reference.description': `Ie. a blog post can reference its author(s)`,
  'fieldGroup.reference.title': `Links`,
  'fieldGroup.rich_text.description': `Compose content w/ text, images, videos...`,
  'fieldGroup.rich_text.title': `Modular content`,
  'fieldGroup.seo.description': `Permalinks, slugs, meta tags`,
  'fieldGroup.seo.title': `SEO`,
  'fieldGroup.text.description': `Titles, names, paragraphs`,
  'fieldGroup.text.title': `Text`,
  'fieldRow.edit': `Settings`,
  'fieldRow.remove': `Delete`,
  'fieldType.boolean': `Boolean`,
  'fieldType.color': `Color`,
  'fieldType.date': `Date`,
  'fieldType.date_time': `DateTime`,
  'fieldType.file': `Single file`,
  'fieldType.float': `Floating-point number`,
  'fieldType.gallery': `Multiple files`,
  'fieldType.image': `Image`,
  'fieldType.integer': `Integer number`,
  'fieldType.json': `JSON`,
  'fieldType.lat_lon': `Geolocation`,
  'fieldType.link': `Single link`,
  'fieldType.links': `Multiple links`,
  'fieldType.rich_text': `Modular content`,
  'fieldType.seo': `SEO meta tags`,
  'fieldType.slug': `Slug`,
  'fieldType.string': `Single-line string`,
  'fieldType.text': `Multiple-paragraph text`,
  'fieldType.video': `Video`,
  'fieldType.options.orderByTime': `Order records by update time`,
  'fieldType.options.orderByField': `Order records by one of its fields`,
  'fieldType.options.orderDnd': `Records can be sorted by editors via drag & drop`,
  'fieldType.options.orderTree': `Records can be organized in a tree by editors`,
  'fieldType.options.view.compact': `Compact view`,
  'fieldType.options.view.tabular': `Tabular view`,
  'fieldType.options.sorting.ascendant': `Ascendent`,
  'fieldType.options.sorting.descendant': `Descendent`,
  'fieldTypeHint.date': `Displays a calendar field`,
  'fieldTypeHint.date_time': `Allows to manage both date and time`,
  'fieldTypeHint.file': `Upload a single image/file`,
  'fieldTypeHint.float': `3.14159265389`,
  'fieldTypeHint.gallery': `Manage a collection of images/files`,
  'fieldTypeHint.image': `Upload a single image`,
  'fieldTypeHint.integer': `1, 2, 3, 5, 8, 13, ...`,
  'fieldTypeHint.link': `Link to a single external record`,
  'fieldTypeHint.links': `Link to a collection of external records`,
  'fieldTypeHint.seo': `Manage title, description, OpenGraph cards, etc.`,
  'fieldTypeHint.slug': `Generate the record permalink based on another text field`,
  'fieldTypeHint.string': `Ideal for titles, headings, etc.`,
  'fieldTypeHint.text': `For Markdown, HTML or plain text`,
  'fieldTypeHint.video': `Supports YouTube/Vimeo URLs`,
  'fileInput.error.notAnImage': `extension must be one of PNG, GIF, JPG, SVG`,
  'fileInput.error.tooBig': `dimensions exceed 150MB`,
  'fileInput.invalidFile': `File invalid: {error}!`,
  'fileInput.uploadError': `Couldn't upload file`,
  'form.editAccessToken.title': `Edit API Token`,
  'form.editAccessTokenForm.refreshToken': `Regenerate API token`,
  'form.editEditorForm.delete': `Delete`,
  'form.editEditorForm.title': `Edit user`,
  'form.editRoleForm.delete': `Delete`,
  'form.editRoleForm.title': `Edit role`,
  'form.slugField.placeholder': `Select one field...`,
  'form.fileInput.buttonLabel': `Upload new file`,
  'form.fileInput.cancelButton': `Cancel upload`,
  'form.fileInput.dragHere': `Drag a file here`,
  'form.fileInput.emptyButtonLabel': `Upload new`,
  'form.fileInput.hint': `Max size 150MB`,
  'form.fileInput.noFiles': `No file specified`,
  'form.fileInput.openMediaGallery': `From library`,
  'form.fileInput.removeImage': `Remove`,
  'form.fileInput.uploadInProgress': `Uploading... { percentage }%`,
  'form.fileGalleryInput.buttonLabel': `Upload new file`,
  'form.fileGalleryInput.cancelButton': `Cancel upload`,
  'form.fileGalleryInput.dragHere': `Drag some files here`,
  'form.fileGalleryInput.emptyButtonLabel': `Upload new`,
  'form.fileGalleryInput.hint': `Max size 150MB`,
  'form.fileGalleryInput.noFile': `No files present`,
  'form.fileGalleryInput.openMediaGallery': `From library`,
  'form.fileGalleryInput.removeImage': `Remove`,
  'form.fileGalleryInput.uploadInProgress': `Uploading... { percentage }%`,
  'form.imageGalleryInput.buttonLabel': `Upload new images`,
  'form.imageGalleryInput.cancelButton': `Cancel upload`,
  'form.imageGalleryInput.dragHere': `Drag some images here`,
  'form.imageGalleryInput.emptyButtonLabel': `Upload new`,
  'form.imageGalleryInput.hint': `Max size 150MB`,
  'form.imageGalleryInput.noFile': `No images present`,
  'form.imageGalleryInput.openMediaGallery': `From gallery`,
  'form.imageGalleryInput.removeImage': `Remove`,
  'form.imageGalleryInput.uploadInProgress': `Uploading... { percentage }%`,
  'form.globalSeoInput.edit': `Edit`,
  'form.globalSeoInput.notProvided': `Global SEO settings not present on this website`,
  'form.globalSeoInput.reset': `Reset`,
  'form.imageInput.buttonLabel': `Upload new image`,
  'form.imageInput.cancelButton': `Cancel upload`,
  'form.imageInput.dragHere': `Drag an image here`,
  'form.imageInput.emptyButtonLabel': `Upload new`,
  'form.imageInput.hint': `Max size 150MB`,
  'form.imageInput.noFile': `No image specified`,
  'form.imageInput.openMediaGallery': `From gallery`,
  'form.imageInput.removeImage': `Remove`,
  'form.imageInput.uploadInProgress': `Uploading... { percentage }%`,
  'form.newAccessToken.title': `New API Token`,
  'form.newEditorForm.title': `Invite a new user`,
  'form.newRoleForm.title': `Create a new role`,
  'formLocaleSwitcher.errorsCount': `{errors} errors`,
  'genericError.ITEM_LOCKED': `The operation cannot be completed as some other user is currently editing this record!`,
  'genericError.REQUIRED_2FA_SETUP': `This project requires every user to turn on 2-factor authentication! Please go to your <a href=\"https://dashboard.datocms.com/account/setup-2fa\">Dashboard</a>.`,
  'genericError.STALE_ITEM_VERSION': `Someone else made a change while you were editing this record, please refresh the page!`,
  'genericError.BATCH_DATA_VALIDATION_IN_PROGRESS': `The schema of this model changed, we're re-running validations over every record in background. Please retry with this operation in a few seconds!`,
  'genericError.INSUFFICIENT_PERMISSIONS': `Your role does not permit this action`,
  'genericError.INVALID_CREDENTIALS': `Credentials are incorrect!`,
  'genericError.INVALID_EMAIL': `Email address is incorrect!`,
  'genericError.INVALID_FORMAT': `Whoops, this shouldn't happen... there's an error on our side :(`,
  'genericError.TITLE_ALREADY_PRESENT': `There can only be one Title field per model`,
  'genericError.UNPUBLISHED_LINK': `Couldn't publish the record, as it links to some unpublished records!`,
  'genericError.UNPUBLISHED_PARENT': `Couldn't publish the record, as the parent record is not published!`,
  'genericError.LINKED_FROM_PUBLISHED_ITEMS': `Couldn't unpublish the record, as some published records are linked to it!`,
  'genericError.PUBLISHED_CHILDREN': `Couldn't unpublish the record, as some children records are published!`,
  'gitlab.branch': `Specify the Git branch you want to build:`,
  'gitlab.button.default': `Save Gitlab settings`,
  'gitlab.token': `Trigger token`,
  'gitlab.trigger': `Step 1: Create Trigger`,
  'gitlab.triggerDescription1': `Go to your Gitlab project, create a new Trigger and paste here the generated trigger token:`,
  'gitlab.trigger.placeholder': `Trigger token`,
  'gitlab.triggerDescription3': `Paste here the curl URL:`,
  'gitlab.trigger.placeholder3': `https://gitlab.com/api/v4/projects/XXX/trigger/pipeline`,
  'gitlab.branch.placeholder': `master`,
  'gitlab.triggerUrl': `Trigger URL`,
  'gitlab.webhook': `Step 2: Create Webhook`,
  'gitlab.webhookDescription': `Copy the following URL and use it to create a Webhook of type \"Pipeline events\":`,
  'gitlab.buildParameters': `Specify any custom environment variables you want to be available during the build`,
  'globalSeo.button.default': `Update SEO fields`,
  'globalSeo.facebookPageUrl': `Facebook page address`,
  'globalSeo.fallbackSeo': `Default SEO settings`,
  'globalSeo.siteName': `Website name`,
  'globalSeo.title': `Fallback title (if not specified)`,
  'globalSeo.description': `Fallback description (if not specified)`,
  'globalSeo.titleSuffix': `Title suffix`,
  'globalSeo.twitterCard': `Twitter card type`,
  'globalSeo.twitterCard.placeholder': `Use global settings defaults`,
  'globalSeo.summaryLargeImage': `Summary with large image`,
  'globalSeo.summary': `Summary`,
  'globalSeo.titleSuffix.placeholder': ` - My website`,
  'globalSeo.twitterAccount': `Twitter account`,
  'globalSeoInput.modalTitle': `Edit SEO settings`,
  'imageInput.error.tooBig': `dimensions exceed 150MB`,
  'imageMetadata.edit': `Edit metadata`,
  'imageMetadata.alt': `Alternate text`,
  'imageMetadata.button.default': `Save`,
  'imageMetadata.title': `Title`,
  'imageMetadata.image': `Image`,
  'imageMetadata.dimensions': `Dimensions`,
  'imageMetadata.date': `Upload date`,
  'imageMetadata.fileType': `File type`,
  'imageMetadata.fileSize': `File size`,
  'imageMetadata.open': `Open`,
  'integration.step1.success': `Command received, hurray!`,
  'item.button.default': `Save record`,
  'item.duplicate': `Duplicate`,
  'item.edit': `Edit { itemType }`,
  'item.remove': `Delete`,
  'item.shortStatus.draft': `Draft`,
  'item.shortStatus.availableVersions': `{number, plural, one {Another version} other {Other {number} versions}} available`,
  'item.shortStatus.published': `Published`,
  'item.shortStatus.updated': `Updated`,
  'item.status.draft.dirty': `Not published (unsaved changes)`,
  'item.status.draft.pristine': `Not published`,
  'item.status.new.dirty': `New record (unsaved changes)`,
  'item.status.new.pristine': `New record`,
  'item.status.published.dirty': `Published (unsaved changes)`,
  'item.status.published.pristine': `Published`,
  'item.status.updated.dirty': `Published (unsaved changes)`,
  'item.status.updated.pristine': `Updated`,
  'item.scheduled': `scheduled on`,
  'item.unpublish': `Unpublish`,
  'item.untitled': `No title`,
  'itemType.add': `Add model`,
  'itemType.addField': `Add {fieldType} field`,
  'itemType.addModularBlock': `Add Modular Content block`,
  'itemType.api_key': `Model ID`,
  'itemType.api_key.hint': `It is generated automatically based on the name and will appear in the API responses`,
  'itemType.api_key.placeholder': `article`,
  'itemType.button.default': `Save model`,
  'itemType.chooseFieldType': `Choose a field type`,
  'itemType.duplicate': `Duplicate`,
  'itemType.edit': `Settings`,
  'itemType.editField': `Edit Field`,
  'itemType.editItemType': `Edit Model`,
  'itemType.editModularBlock': `Edit Modular Content block`,
  'itemType.modularBlock.add': `New block`,
  'itemType.id': `Model ID`,
  'itemType.name': `Name`,
  'itemType.name.hint': `Please write it down in singular form (ie. \"Article\`, not \"Articles\")`,
  'itemType.name.placeholder': `Article`,
  'itemType.orderingDirection': `Ordering direction`,
  'itemType.orderingField': `Select the ordering field`,
  'itemType.orderingMethod': `How should we order this collection of records?`,
  'itemType.row.add': `Add new field`,
  'itemType.row.delete': `Delete`,
  'itemType.row.edit': `Settings`,
  'itemType.collectionAppeareance': `Records collection visualization mode`,
  'itemType.singleton': `Single instance?`,
  'itemType.singleton.guide': `Read more about single-instance models vs collections in our docs`,
  'itemType.singleton.hint': `Do you need to manage a collection of records of this kind, or just a single one?`,
  'itemType.draftMode': `Enable draft/published system?`,
  'itemType.draftMode.guide': `Read more about draft/published system in our docs`,
  'itemType.draftMode.hint': `If enabled, changes made to records won't be immediately published but instead put in draft`,
  'itemType.allLocalesRequired': `All locales required?`,
  'itemType.allLocalesRequired.hint': `Records must define values for all the site's locales`,
  'itemType.validator.placeholder': `Select one (or more) model(s)...`,
  'seoField.validator.placeholder': `Select one field...`,
  'latLonInput.search': `Search address...`,
  'mediaArea.assets.count': `{count, plural, =0 {No asset present} one {1 asset} other {{count} assets}}`,
  'mediaArea.assets.delete': `Delete`,
  'mediaArea.assets.upload': `Upload new assets`,
  'mediaArea.assets.delete.confirm': `Do you really want to delete this asset?`,
  'mediaArea.assets.delete.selection': `Do you really want to delete {count} assets?`,
  'mediaArea.assets.delete.unused': `Delete all unused?`,
  'mediaArea.assets.deselect': `{count, plural, one {Deselect} other {Deselect all}}`,
  'mediaArea.assets.selected': `{count, plural, one {One asset selected} other {{count} assets selected}}`,
  'mediaArea.bytesUsed': `{currentBytes} of {availableBytes} used`,
  'mediaArea.bytesUsed.unlimited': `{currentBytes} used (unlimited space available)`,
  'mediaArea.details': `Upload details`,
  'mediaArea.empty.title': `Nothing to see here!`,
  'mediaArea.empty.sub': `Would you like to upload something?`,
  'mediaArea.empty.sub2': `Drop some files here, or press the upload button above.`,
  'mediaArea.filterBy.all': `All`,
  'mediaArea.filterBy.file': `Documents`,
  'mediaArea.filterBy.image': `Images`,
  'mediaArea.filterBy.not_used': `Not Used`,
  'mediaArea.filterBy.other': `Other`,
  'mediaArea.filterBy.video': `Videos`,
  'mediaArea.thumbs': `Thumbs`,
  'mediaArea.type': `Type`,
  'menu.settings': `Settings`,
  'menuItem.button.default': `Save Menu item`,
  'menuItem.itemType': `Connected model`,
  'menuItem.label': `Label`,
  'menuItem.linkType': `Point this to`,
  'menuItem.externalUrl': `External URL`,
  'menuItem.filter': `Filters`,
  'menuItems.add': `Add menu item...`,
  'menuItems.noMenuItems': `Your navigation bar is empty... let your editors create new content for all the Models available!`,
  'menuPage.noItemType': `No model`,
  'menuitem.add': `Add Menu item`,
  'menuitem.edit': `Edit Menu item`,
  'menuitem.fieldrow.delete': `Delete`,
  'menuitem.fieldrow.edit': `Edit`,
  'menuitem.link.nothing': `Nothing`,
  'menuitem.link.model': `Model`,
  'menuitem.link.external': `External URL`,
  'richText.validator.placeholder':
    'Select the models that will be used as blocks...',
  'admin.modularBlock.destroyConfirm.title': `Delete modular block`,
  'admin.modularBlock.destroyConfirm.question': `This modular block is not used in any other field, do you want to completely remove it from the administrative area?`,
  'admin.modularBlock.destroyConfirm.ok': `Yes, delete it`,
  'admin.modularBlock.destroyConfirm.cancel': `Keep it, I'll use it later`,

  'messages.confirm.destroySiteLocale.title': `Delete locale`,
  'messages.confirm.destroySiteLocale.question': `You are removing the following languages from the project: {locales}. By removing these languages you will delete ALL content associated with them. Are you REALLY sure you want to proceed?`,
  'messages.confirm.destroySiteLocale.ok': `Yes, delete all content`,
  'messages.confirm.destroySiteLocale.cancel': `Cancel`,

  'messages.confirm.destroyWebhook.title': `Delete webhook`,
  'messages.confirm.destroyWebhook.question': `Are you sure you want to delete this webhook?`,
  'messages.confirm.destroyWebhook.ok': `Yes, delete`,
  'messages.confirm.destroyWebhook.cancel': `Cancel`,

  'messages.confirm.destroyPlugin.title': `Delete plugin`,
  'messages.confirm.destroyPlugin.question': `Are you sure you want to delete this plugin?`,
  'messages.confirm.destroyPlugin.ok': `Yes, delete`,
  'messages.confirm.destroyPlugin.cancel': `Cancel`,

  'messages.confirm.destroyDeploymentEnvironment.title': `Delete deployment environment`,
  'messages.confirm.destroyDeploymentEnvironment.question': `Are you sure you want to delete this deployment environment?`,
  'messages.confirm.destroyDeploymentEnvironment.ok': `Yes, delete`,
  'messages.confirm.destroyDeploymentEnvironment.cancel': `Cancel`,

  'messages.confirm.destroyRole.title': `Delete role`,
  'messages.confirm.destroyRole.question': `Are you sure you want to delete this role?`,
  'messages.confirm.destroyRole.ok': `Yes, delete`,
  'messages.confirm.destroyRole.cancel': `Cancel`,

  'messages.confirm.destroyItemTypeFilter.title': `Delete filter`,
  'messages.confirm.destroyItemTypeFilter.question': `Are you sure you want to delete this filter?`,
  'messages.confirm.destroyItemTypeFilter.ok': `Yes, delete`,
  'messages.confirm.destroyItemTypeFilter.cancel': `Cancel`,

  'messages.confirm.destroyMenuItem.title': `Delete menu item`,
  'messages.confirm.destroyMenuItem.question': `Are you sure you want to delete this menu item?`,
  'messages.confirm.destroyMenuItem.ok': `Yes, delete`,
  'messages.confirm.destroyMenuItem.cancel': `Cancel`,

  'messages.confirm.destroyAccessToken.title': `Delete API token`,
  'messages.confirm.destroyAccessToken.question': `Are you sure you want to delete this API token?`,
  'messages.confirm.destroyAccessToken.ok': `Yes, delete`,
  'messages.confirm.destroyAccessToken.cancel': `Cancel`,

  'messages.confirm.regenerateAccessToken.title': `Regenerate API token`,
  'messages.confirm.regenerateAccessToken.question': `Are you sure you want to regenerate this API token?`,
  'messages.confirm.regenerateAccessToken.ok': `Yes, regenerate`,
  'messages.confirm.regenerateAccessToken.cancel': `Cancel`,

  'messages.confirm.destroyUser.title': `Remove collaborator`,
  'messages.confirm.destroyUser.question': `Are you sure you want to remove this collaborator from the project?`,
  'messages.confirm.destroyUser.ok': `Yes, remove`,
  'messages.confirm.destroyUser.cancel': `Cancel`,

  'messages.confirm.deleteScheduledPublication.title': `Cancel scheduled publication?`,
  'messages.confirm.deleteScheduledPublication.question': `This record will no longer be automatically published. Do you want to proceed?`,
  'messages.confirm.deleteScheduledPublication.ok': `Yes, stop automatic publication`,
  'messages.confirm.deleteScheduledPublication.cancel': `Cancel`,

  'messages.confirm.destroyRecord.title': `Delete record?`,
  'messages.confirm.destroyRecord.question': `Are you sure you want to delete this record? This operation is not reversible!`,
  'messages.confirm.destroyRecord.ok': `Yes, delete this record`,
  'messages.confirm.destroyRecord.cancel': `Cancel`,

  'messages.confirm.removeReferences.title': `Remove references?`,
  'messages.confirm.removeReferences.question': `This records is referenced in a number of other published records. If you proceed, those references will be removed.`,
  'messages.confirm.removeReferences.ok': `Yes, delete and remove references`,
  'messages.confirm.removeReferences.cancel': `Cancel`,

  'messages.confirm.destroyAsset.title': `Delete asset?`,
  'messages.confirm.destroyAsset.question': `Are you sure you want to delete this asset? This operation is not reversible!`,
  'messages.confirm.destroyAsset.ok': `Yes, delete this asset`,
  'messages.confirm.destroyAsset.cancel': `Cancel`,

  'messages.confirm.assets.batch.delete.title': `Delete {count, plural, one { the asset? } other { {count} assets?} }`,
  'messages.confirm.assets.batch.delete.question': `Are you sure you want to delete {count, plural, one { this asset } other { {count} assets} }? This operation is not reversible!`,
  'messages.confirm.assets.batch.delete.ok': `Yes, delete {count, plural, one { this asset } other { {count} assets} }`,
  'messages.confirm.assets.batch.delete.cancel': `Cancel`,

  'messages.confirm.batch.delete.title': `Delete {count, plural, one { the record } other { {count} records?} }`,
  'messages.confirm.batch.delete.question': `Are you sure you want to delete {count, plural, one { this record } other { {count} records} }? This operation is not reversible!`,
  'messages.confirm.batch.delete.ok': `Yes, delete {count, plural, one { this record } other { {count} records} }`,
  'messages.confirm.batch.delete.cancel': `Cancel`,

  'messages.confirm.batch.publish.title': `Publish {count, plural, one { the record } other { {count} records} }`,
  'messages.confirm.batch.publish.question': `Are you sure you want to publish {count, plural, one { this record } other { {count} records} }?`,
  'messages.confirm.batch.publish.ok': `Yes, publish {count, plural, one { this record } other { {count} records} }`,
  'messages.confirm.batch.publish.cancel': `Cancel`,

  'messages.confirm.batch.unpublish.title': `Unpublish {count, plural, one { the record } other { {count} records} }`,
  'messages.confirm.batch.unpublish.question': `Are you sure you want to unpublish {count, plural, one { this record } other { {count} records} }?`,
  'messages.confirm.batch.unpublish.ok': `Yes, unpublish {count, plural, one { this record } other { {count} records} }`,
  'messages.confirm.batch.unpublish.cancel': `Cancel`,

  'messages.confirm.destroyItemType.title': `Remove model`,
  'messages.confirm.destroyItemType.question': `By removing this model you will permanently delete all of its records. Are you sure you want to proceed?`,
  'messages.confirm.destroyItemType.ok': `Yes, delete this model`,
  'messages.confirm.destroyItemType.cancel': `Cancel`,

  'messages.confirm.destroyBlock.title': `Remove modular block`,
  'messages.confirm.destroyBlock.question': `By removing this block you will delete ALL content associated with it. Are you sure you want to proceed?`,
  'messages.confirm.destroyBlock.ok': `Yes, delete this block`,
  'messages.confirm.destroyBlock.cancel': `Cancel`,

  'messages.confirm.destroyField.title': `Delete field`,
  'messages.confirm.destroyField.question': `By removing this field you will delete ALL content associated with it. Are you sure you want to proceed?`,
  'messages.confirm.destroyField.ok': `Yes, delete this field`,
  'messages.confirm.destroyField.cancel': `Cancel`,

  'messages.confirm.destroyLocale.title': `Delete locale`,
  'messages.confirm.destroyLocale.question': `Are you sure you want to proceed deleting content in this locale?`,
  'messages.confirm.destroyLocale.ok': `Yes, delete`,
  'messages.confirm.destroyLocale.cancel': `Cancel`,

  'messages.confirm.convertField.title': `Convert field`,
  'messages.confirm.convertField.question': `Are you sure you want to convert this field? This operation is not reversible.`,
  'messages.confirm.convertField.ok': `Yes, convert`,
  'messages.confirm.convertField.cancel': `Cancel`,

  'messages.confirm.changeCreator.title': `Change creator`,
  'messages.confirm.changeCreator.question': `Are you sure you want to change the creator of this record?`,
  'messages.confirm.changeCreator.ok': `Yes, change it`,
  'messages.confirm.changeCreator.cancel': `Cancel`,

  'messages.notsaved.title': `Discard changes`,
  'messages.notsaved.question': `There are some changes to the data inserted in the form which are not saved. Are you sure you want to leave the page?`,
  'messages.notsaved.ok': `Yes, discard changes`,
  'messages.notsaved.cancel': `Cancel`,

  'modal.close': `Close`,
  'modularBlock.add': `Add modular block`,
  'modularBlock.existing': `Pick existing`,
  'modularBlock.new': `Create new`,
  'modularBlock.edit': `Edit modular block`,
  'nav.support': `Ask for support`,
  'nav.new': `What's new`,
  'nav.docs': `Docs`,
  'nav.adminArea': `Settings`,
  'nav.contentTabHint.content': `Inside this tab you (and the site editors) can manage the content of the website. Try to create some new content now!`,
  'nav.contentTabHint.title': `Great, now it's time write some content!`,
  'nav.documentation': `Docs/Support`,
  'nav.logout': `Log out`,
  'nav.manageItemTypes': `Content`,
  'nav.mediaArea': `Media`,
  'changelog.changes': `Latest changes`,
  'changelog.changelog': `changelog`,
  'changelog.read': `Read all the announcements on our {link}`,
  'changelog.post': `Read the complete post »`,
  'navigationBar.dashboard': `Back to Dashboard`,
  'navigationBar.visitSite': `Visit site`,
  'navigationBar.visitEnvSite': `Visit {env} site`,
  'netlify.success': `Great, integration with Netlify project \"{name}\" completed successfully, you can now save your settings!`,
  'netlify.branch': `Git branch to build:`,
  'netlify.branch.placeholder': `master`,
  'netlify.branch.hint': `If not specified, the project's production branch will be used`,
  'netlify.button.default': `Submit`,
  'newItem.filter': `Filter results...`,
  'newItem.title': `Add {name}`,
  'itemsCollection.title': `{name} collection`,
  'noAuth.completeRegistration.create.failure': `Couldn't complete the registration process!`,
  'noAuth.completeRegistration.create.success': `Registration completed, welcome on board!`,
  'noAuth.completeRegistration.title': `Complete registration`,
  'noAuth.signIn.create.failure': `Couldn't login!`,
  'noAuth.signIn.create.missingToken': `Couldn't login, missing token`,
  'noAuth.signIn.create.success': `Successfully logged in, welcome!`,
  'noAuth.signIn.logout.success': `Successfully logged out, bye!`,
  'noAuth.signIn.title': `Log in`,
  'noAuth.signIn.require2fa': `For security reasons, the owner of this project has requested that every member activates a two-factor authentication. Please enable it on your dashboard`,
  'noMatch.body': `Sorry, but the page you've requested is not here. It is possible that it has been moved, or maybe it doesn't exist anymore.`,
  'noMatch.cta': `Go to Homepage`,
  'noMatch.title': `404?!`,
  'notifications.hide': `Hide this message`,
  'permissionDenied.subtitle': `Your account does not have enough priviledges to access this area`,
  'permissionDenied.title': `Permission denied`,
  'richText.add': `Add new`,
  'richText.add.single': `New {itemType}`,
  'richText.add.multiple': `Create new...`,
  'richText.dropdown.collapse': `Collapse all`,
  'richText.dropdown.expand': `Expand all`,
  'richText.dropdown.moveUp': `Move up`,
  'richText.dropdown.moveDown': `Move down`,
  'richText.dropdown.removeBlock': `Remove block`,
  'richText.copyStructure': `Copy structure from {locale}`,
  'richText.chooseItemType': `No models available, please edit this field settings`,
  'filterForm.addFilter': `Add Filter`,
  'scrapeFailureReason.MISSING_FRONTEND_URL': `No frontend URL is configured for this environment!`,
  'section.managePreferences': `Manage global site settings`,
  'semaphore.authenticationToken': `Step 1: Find your authentication token`,
  'semaphore.authenticationTokenDescription': `Go to your account Settings page and paste here your Authentication Token:`,
  'semaphore.branch': `Specify the Git branch you want to build:`,
  'semaphore.button.default': `Save Semaphore settings`,
  'semaphore.notification': `Step 3: Create a notification`,
  'semaphore.notificationDescription': `Copy the following URL and use it to create a Webhook notification in your Semaphore project Settings page:`,
  'semaphore.projectHashId': `Step 2: Find your Project hash_id`,
  'semaphore.projectHashIdDescription': `Open to your project Settings page, go in the Admin tab and paste here your project's hash_id:`,
  'semaphore.token.placeholder': `Authentication token`,
  'semaphore.hash.placeholder': `Project hash_id`,
  'semaphore.branch.placeholder': `master`,
  'seo.button.default': `Save SEO settings`,
  'seo.description': `Description`,
  'seo.image': `Sharing image (Facebook, Twitter)`,
  'seo.title': `Title`,
  'seoInput.blank': `No SEO setting configured`,
  'seoInput.edit': `Edit`,
  'seoInput.modalTitle': `Edit SEO settings`,
  'seoInput.remove': `Reset`,
  'settings.button.default': `Save settings`,
  'settings.favicon': `Favicon`,
  'settings.globalSeo': `Global SEO settings`,
  'settings.noIndex': `Prevent your site from being indexed by search engines?`,
  'signin.button.default': `Login`,
  'signin.email': `Email`,
  'signin.otp': `Authentication code`,
  'signin.otp.hint': `Open the two-factor authentication app on your device and enter your authentication code to verify your identity`,
  'signin.otp.placeholder': `123 456`,
  'signin.password': `Password`,
  'signin.resetPassword': `Forgot password?`,
  'form.editDeploymentEnvironmentForm.title': `Edit Deployment environment`,
  'form.newDeploymentEnvironmentForm.title': `New Deployment environment`,
  'form.editDeploymentEnvironmentForm.delete': `Delete`,
  'site.button.default': `Save Settings`,
  'site.deployAdapters.circle_ci': `CircleCI`,
  'site.deployAdapters.custom': `Custom webhook`,
  'site.deployAdapters.gitlab': `Gitlab`,
  'site.deployAdapters.netlify': `Netlify`,
  'site.deployAdapters.netlifySub': `Recommended for new sites: one-click setup, handles site building + CDN hosting`,
  'site.deployAdapters.none': `None`,
  'site.deployAdapters.semaphore': `Semaphore`,
  'site.deployAdapters.travis': `Travis`,
  'site.logo.label': `Logo`,
  'site.locales.docs': `Read more about localization in our docs`,
  'site.locales.hint': `Please select the languages you want to enable in this administrative area`,
  'site.locales.label': `Supported languages`,
  'site.name.label': `Administrative area title`,
  'site.require2fa.hint': `If enabled, users of this site will be required to insert a one-time-password to sign in.`,
  'site.require2fa.label': `Two-factor authentication`,
  'deploymentEnvironment.buildMethod': `Build method`,
  'deploymentEnvironment.options': `Options`,
  'deploymentEnvironment.deployAdapter': `Please select the external service you're using to build and deploy your static website:`,
  'deploymentEnvironment.name.label': `Name`,
  'deploymentEnvironment.frontendUrl.hint': `Please specify the URL where the final static website will be hosted`,
  'deploymentEnvironment.frontendUrl.label': `Website frontend URL`,
  'deploymentEnvironment.spidering.guide': `Learn how to integrate DatoCMS search into your site in our docs`,
  'deploymentEnvironment.spidering.hint': `Everytime your site is built, we'll respider it to get updated content`,
  'deploymentEnvironment.spidering.hintWithLimit': `Everytime your site gets deployed, we'll respider it to get updated content. Your plan for this site limits the number of indexable pages to {limit}.`,
  'deploymentEnvironment.spidering.label': `Enable Site search`,
  'deploymentEnvironment.schedule.label': `Automatically trigger a build on scheduled publications`,
  'site.ssg.guide': `Learn how to integrate your static website with DatoCMS in our docs`,
  'site.ssg.hint': `DatoCMS supports every static website generator, offering a simple, agnostic CLI integration tool`,
  'site.ssg.label': `Your project static website generator`,
  'site.themeHue.hint': `Feel free to change the primary color of this administrative area to better match your project identity`,
  'site.themeHue.label': `Theme color`,
  'site.timezone': `Timezone`,
  'slug.urlPrefix': `URL prefix`,
  'slug.urlPrefix.hint': `Specify the real URL prefix for this slug (will be shown in the editor)`,
  'slug.urlPrefix.placeholder': `http://www.example.com/items/`,
  'ssg.gatsby': `Gatsby`,
  'ssg.hexo': `Hexo`,
  'ssg.hugo': `Hugo`,
  'ssg.jekyll': `Jekyll`,
  'ssg.metalsmith': `Metalsmith`,
  'ssg.middleman': `Middleman`,
  'ssg.other': `Other`,
  'travis.branch': `Specify the Git branch you want to build:`,
  'travis.button.default': `Save Travis settings`,
  'travis.config': `If you want to <a target=\"_blank\" href=\"https://docs.travis-ci.com/user/triggering-builds/\">override the some settings contained in your .travis.yml</a>, you can paste here the JSON payload for the <code>\"config\"</code> parameter of the build request:`,
  'travis.configHint': `This can be useful to pass different environment variables, script commands or deployment settings during the build`,
  'travis.repo': `Specify the Github repository of your project:`,
  'travis.selectRepo': `Step 1: Specify your repository`,
  'travis.trigger': `Step 2: Obtain API token`,
  'travis.triggerDescription1': `Follow <a target=\"_blank\" href=\"https://docs.travis-ci.com/user/triggering-builds/\">this guide</a> to obtain your API token, then paste it here:`,
  'travis.webhook': `Step 3: Edit .travis.yml`,
  'travis.webhookDescription': `Add the following lines to your .travis.yml config file:`,
  'travis.repo.placeholder': `username/repo`,
  'travis.branch.placeholder': `master`,
  'travis.trigger.placeholder': `API token`,
  'travis.config.placeholder': `'{\n  "script": "echo FOO" \n}'`,
  'validator.date_range.hint': `Specify an early and/or latest allowed date for this field`,
  'validator.date_range.title': `Accept only specified date range`,
  'validator.date_time_range.hint': `Specify an early and/or latest allowed date time for this field`,
  'validator.date_time_range.title': `Accept only specified date time range`,
  'validator.enum.hint': `You won't be able to publish a record if the field value is not in the list of specified values`,
  'validator.enum.title': `Accept only specified values`,
  'validator.enum.valuePlaceholder': `foo, bar, qux`,
  'validator.extension.hint': `You won't be able to publish a record if the file doesn't end with one the specified values`,
  'validator.extension.title': `Accept only specified extensions`,
  'validator.file_size.hint': `Specify a minimum and/or maximum allowed file size`,
  'validator.file_size.title': `Accept only specified file size`,
  'validator.image_dimensions.title': `Accept only specified image dimensions`,
  'validator.image_dimensions.hint': `Specify a minimum and/or maximum width and height for images`,
  'validator.format.hint': `Make this field match a pattern: e-mail address, URI, or a custom regular expression`,
  'validator.format.title': `Match a specific pattern`,
  'validator.item_item_type.hint': `Make this field only accept records from specified model(s)<br/><a href=\"https://www.datocms.com/docs/content-modelling/links\" target=\"_blank\">Read more about Link fields in our docs</a>`,
  'validator.item_item_type.title': `Accept only specified model`,
  'validator.items_item_type.title': `Accept only specified models`,
  'validator.length.hint': `Specify a minimum and/or maximum allowed number of characters`,
  'validator.length.title': `Limit character count`,
  'validator.links.items_item_type.hint': `Make this field only accept records from specified model(s)<br/><a href=\"https://www.datocms.com/docs/content-modelling/links\" target=\"_blank\">Read more about Link fields in our docs</a>`,
  'validator.links.items_item_type.title': `Accept only specified model`,
  'validator.number_range.hint': `Specify a minimum and/or maximum value`,
  'validator.number_range.title': `Range`,
  'validator.required.hint': `You won't be able to publish a record if this field is empty`,
  'validator.required.title': `Required`,
  'validator.rich_text_blocks.hint': `The idea behind this field is to give your editors the choice to compose their content by alternating an arbitrary number of lower-level models that will be used as \"building blocks\". Authors will be able to choose, populate and reorder these blocks as needed. <a href=\"https://www.datocms.com/docs/content-modelling/modular-content\" target=\"_blank\">Read more in our docs</a>`,
  'validator.rich_text_blocks.title': `Specify the models to be used as \"building blocks\" for this field`,
  'validator.size.hint': `Specify a minimum and/or maximum allowed number of records`,
  'validator.size.title': `Accept only a specified number of records`,
  'validator.unique.hint': `You won't be able to publish a record if there is an existing record with identical content`,
  'validator.unique.title': `Unique field`,
  'validator.slug_title_field.title': `Reference field`,
  'validator.slug_title_field.hint': `Field from which it will be automatically generated a slug, unless manually specified`,
  'validators.date_range.and': `and`,
  'validators.date_range.between': `Between`,
  'validators.date_range.max': `No more than`,
  'validators.date_range.maxValue': `max`,
  'validators.date_range.min': `At least`,
  'validators.date_range.minValue': `min`,
  'validators.date_time_range.and': `and`,
  'validators.date_time_range.between': `Between`,
  'validators.date_time_range.max': `No more than`,
  'validators.date_time_range.maxValue': `max`,
  'validators.date_time_range.min': `At least`,
  'validators.date_time_range.minValue': `min`,
  'validators.enum.hint': `Separate each value with a comma`,
  'validators.enum.valuePlaceholder': `foo, bar, qux`,
  'validators.extension.csv': `Custom`,
  'validators.extension.document': `Document`,
  'validators.extension.hint': `Separate each value with a comma (match is case insensitive)`,
  'validators.extension.image': `Image`,
  'validators.extension.valuePlaceholder': `zip, pdf`,
  'validators.extension.video': `Video`,
  'validators.file_size.and': `and`,
  'validators.file_size.between': `Between`,
  'validators.file_size.max': `No more than`,
  'validators.file_size.maxValue': `max`,
  'validators.file_size.min': `At least`,
  'validators.file_size.minValue': `min`,
  'validators.file_size.unit.b': `B`,
  'validators.file_size.unit.kib': `KB`,
  'validators.file_size.unit.mib': `MB`,
  'validators.format.custom': `Custom format`,
  'validators.format.email': `Email`,
  'validators.format.hint': `Please insert a regular expression`,
  'validators.format.placeholder': `^(foo|bar)$`,
  'validators.format.url': `URL`,
  'validators.length.and': `and`,
  'validators.length.between': `Between`,
  'validators.length.eq': `Exactly`,
  'validators.length.eqValue': `value`,
  'validators.length.max': `No more than`,
  'validators.length.maxValue': `max`,
  'validators.length.min': `At least`,
  'validators.length.minValue': `min`,
  'validators.dimensions.width': `width`,
  'validators.dimensions.height': `height`,
  'validators.number_range.and': `and`,
  'validators.number_range.between': `Between`,
  'validators.number_range.max': `No more than`,
  'validators.number_range.maxValue': `max`,
  'validators.number_range.min': `At least`,
  'validators.number_range.minValue': `min`,
  'validators.size.and': `and`,
  'validators.size.between': `Between`,
  'validators.size.eq': `Exactly`,
  'validators.size.eqValue': `value`,
  'validators.size.multipleOf': `The number of records must also be multiple of`,
  'validators.size.multipleOfValue': `number`,
  'validators.size.max': `No more than`,
  'validators.size.maxValue': `max`,
  'validators.size.min': `At least`,
  'validators.size.minValue': `min`,
  'validators.size_range.between': `Between`,
  'validators.size_range.eq': `Exactly`,
  'validators.size_range.max': `No more than`,
  'validators.size_range.min': `At least`,
  'videoInput.hint': `Copy and paste here the address of the page containing a YouTube, Vimeo or Facebook video:`,
  'videoInput.invalidUrl': `Invalid URL!`,
  'videoInput.noVideo': `No video specified`,
  'videoInput.remove': `Remove video`,
  'videoInput.placeholder': `https://www.youtube.com/watch?v=aqz-KE-bpKQ`,
  'itemTypeForm.tab.basic': `Basic info`,
  'itemTypeForm.tab.extra': `Additional settings`,
  'globalError.INSUFFICIENT_PERMISSIONS': `Your role does not permit this action`,
  'globalError.INVALID_SITE.title': `This project doesn't exist!`,
  'globalError.INVALID_SITE.body': `Sorry, but no DatoCMS project exists under this domain. If you think this is an error, please contact us on <a href='https://www.datocms.com/support' target='_blank'>the support page</a>.`,
  'globalError.DEACTIVATED_SITE.title': `Project deactivated!`,
  'globalError.DEACTIVATED_SITE.body': `Sorry but due to invoicing problems this project has been temporarly deactivated. Please contact your administrators to solve the issue.`,
  'globalError.UNDER_MAINTENANCE.title': `We'll be back soon!`,
  'globalError.UNDER_MAINTENANCE.body': `Sorry for the inconvenience but we're performing some maintenance at the moment. You can check our <a href='https://status.datocms.com' target='_blank'>Status page</a> to follow progress or contact us on <a href='https://www.datocms.com/support' target='_blank'>the support page</a>.`,

  'role.button.default': `Save role`,
  'role.canEditFavicon': `Can modify site's favicon, global SEO settings and site indexing policy`,
  'role.canEditSchema': `Can modify models, fields and navigation bar`,
  'role.canEditSite': `Can modify site languages, deploy settings and timezones`,
  'role.canManageAccessTokens': `Can manage API Tokens`,
  'role.canManageSharedFilters': `Can create shared filters`,
  'role.canManageDeploymentEnvironments': `Can manage deployment environments`,
  'role.canManageWebhooks': `Can manage webhooks`,
  'role.canManageUsers': `Can manage roles and invite/remove collaborators`,
  'role.canPerformSiteSearch': `Can perform Site Search API calls`,
  'role.canPublishToProduction': `Can publish to Production environment`,
  'role.canPublishToStaging': `Can publish to Staging environment`,
  'role.canPublishRecords': `Can publish records`,
  'role.name': `Name`,
  'role.content': `Content`,
  'role.publishing': `Publishing`,
  'role.whoCan': `Collaborators/API tokens on this role CAN:`,
  'role.whoCannot': `Collaborators/API tokens on this role CANNOT:`,
  'role.whoCanPublish': `Collaborators/API tokens on this role CAN publish:`,
  'role.whoCannotPublish': `Collaborators/API tokens on this role CANNOT publish:`,
  'role.admin': `Admin`,
  'role.canEditItemsCreatedBy': `Can edit records created by`,
  'role.select.creator.anyone': `Created by anyone`,
  'role.select.creator.self': `Created by the user itself`,
  'role.select.creator.role': `Created by users with same role`,
  'role.select.creator.negativeAnyone': `Created by anyone`,
  'role.select.creator.negativeSelf': `Created by users different than itself`,
  'role.select.creator.negativeRole': `Created by users with different role`,
  'role.select.model.all': `All records`,
  'role.select.model.none': `Any record`,
  'role.select.action.all': `Perform all actions on`,
  'role.select.action.none': `Perform any action on`,
  'role.select.action.read': `Read`,
  'role.select.action.duplicate': `Create/duplicate`,
  'role.select.action.update': `Edit`,
  'role.select.action.unpublish': `Publish/unpublish`,
  'role.select.action.delete': `Delete`,
  'role.select.action.editCreator': `Edit creator`,
  'role.select.action.takeOver': `Take over`,
  'role.form.addRule': `Add new rule`,
  'role.canPublish.all': `All deployment environments`,

  'planUpgradeRequired.users.description': `You've reached the maximum number of users your plan allows to invite to the project.`,
  'planUpgradeRequired.otp.description': `Two-factor authentication cannot be on the current plan.`,
  'planUpgradeRequired.items.description': `You've reached the maximum number of records your plan allows to create.`,
  'planUpgradeRequired.item_types.description': `You've reached the maximum number of models your plan allows to create.`,
  'planUpgradeRequired.roles.description': `You've reached the maximum number of roles your plan allows to create.`,
  'planUpgradeRequired.locales.description': `You've reached the maximum number of locales your plan allows.`,
  'planUpgradeRequired.uploadable_bytes.description': `You've reached the file storage limits of your site's current plan.`,
  'planUpgradeRequired.plugins.description': `You've reached the maximum number of plugins your plan allows.`,
  'planUpgradeRequired.deployment_environments.description': `You've reached the maximum number of deployment environments your plan allows.`,

  'genericError.PLAN_UPGRADE_REQUIRED': `Cannot proceed, please upgrade plan!`,

  'editor.deploymentEnvironment.update.success': `Deployment environment successfully updated!`,
  'editor.deploymentEnvironment.update.failure': `Couldn't update deployment environment!`,
  'editor.deploymentEnvironment.create.success': `Deployment environment successfully created!`,
  'editor.deploymentEnvironment.create.failure': `Couldn't create deployment environment!`,
  'editor.deploymentEnvironment.destroy.success': `Deployment environment successfully deleted!`,
  'editor.deploymentEnvironment.destroy.failure': `Couldn't delete deployment environment!`,

  'form.newPlugin.title': `Create new plugin`,
  'plugin.createPrivate': `Create private plugin`,
  'plugin.button.default': `Save plugin settings`,
  'plugin.name': `Plugin name`,
  'plugin.description': `Small description`,
  'plugin.url': `Entry point URL`,
  'plugin.url.hint': `Read more about plugins entry point <a href=\"https://www.datocms.com/docs/guides/building-plugins/entry-point\">in our guide</a>`,
  'plugin.fromUrl': `Insert the name of a DatoCMS NPM module, or paste a public GitHub link to the plugin's <code>package.json</code>:`,
  'plugin.fromUrl.hint': `You can browse some extensions in our <a href=\"https://github.com/datocms/plugins\">Github repository</a>`,
  'plugin.field_types': `Field types`,
  'plugin.field_types.hint': `Select the types of field where it will be possible to use the plugin`,
  'plugin.parameter_definitions': `Parameter definitions`,
  'plugin.parameter_definitions.hint': `Read more about parameter definitions <a href=\"https://www.datocms.com/docs/guides/building-plugins/creating-a-new-plugin#configuration-parameters\">in our guide</a>`,
  'form.editPlugin.title': `Edit Plugin`,
  'form.editPlugin.info': `Plugin info`,
  'form.editPlugin.update': `Update to v{version}`,
  'form.editPlugin.installableOn': `<strong>Installable on:</strong> {fieldTypes} fields`,
  'form.editPlugin.pluginType': `Plugin type:`,
  'form.editPlugin.newVersion': `A new version of <strong>{pluginName}</strong> is now available!`,
  'form.editPlugin.visit': `Visit plugin homepage for instructions »`,
  'form.editPlugin.fieldsUsing': `Fields using this plugin`,
  'form.editPlugin.noFieldsUsing': `No field is using this plugin yet!`,
  'form.editPlugin.settings': `Plugin settings`,

  'webhookCall.details.pages': `Indexed pages`,
  'webhookCall.details.pages_count': `Number of pages indexed`,
  'webhookCall.details.requestBody': `Request Body`,
  'webhookCall.details.requestHeaders': `Request Headers`,
  'webhookCall.details.responseBody': `Response Body`,
  'webhookCall.details.responseHeaders': `Response Headers`,
  'webhookCall.details.responseStatusCode': `Response Status Code`,
  'webhookCall.details.timestamp': `Event Timestamp`,
  'webhookCall.details.requestUrl': `Request Url`,
  'webhookCall.resendWebhook': `Resend`,
  'webhookCall.detailsTitle': `Event details`,
  'admin.webhookCalls.title': `Webhooks activity log`,
  'admin.webhookCalls.noEvents.title': `No activity so far`,
  'admin.webhookCalls.instructions': `Here you can monitor your webhooks in real-time. If something goes wrong, this is the first place to look for hints`,

  'itemType.titleField': `Title field`,

  'markdownEditor.toolbar': `Toolbar buttons`,
  'markdownEditor.toolbar.hint': `Configure which formatting options will be provided to editors`,

  'markdownEditor.toolbar.heading': `Heading`,
  'markdownEditor.toolbar.bold': `Bold`,
  'markdownEditor.toolbar.italic': `Italic`,
  'markdownEditor.toolbar.strikethrough': `Strikethrough`,
  'markdownEditor.toolbar.unordered_list': `Unordered list`,
  'markdownEditor.toolbar.ordered_list': `Ordered list`,
  'markdownEditor.toolbar.quote': `Quote`,
  'markdownEditor.toolbar.link': `Add link`,
  'markdownEditor.toolbar.image': `Add image`,
  'markdownEditor.toolbar.fullscreen': `Fullscreen`,

  'wysiwygEditor.toolbar': `Toolbar buttons`,
  'wysiwygEditor.toolbar.hint': `Configure which formatting options will be provided to editors`,

  'wysiwygEditor.toolbar.format': `Format`,
  'wysiwygEditor.toolbar.bold': `Bold`,
  'wysiwygEditor.toolbar.italic': `Italic`,
  'wysiwygEditor.toolbar.strikethrough': `Strikethrough`,
  'wysiwygEditor.toolbar.unordered_list': `Unordered list`,
  'wysiwygEditor.toolbar.ordered_list': `Ordered list`,
  'wysiwygEditor.toolbar.quote': `Quote`,
  'wysiwygEditor.toolbar.link': `Add link`,
  'wysiwygEditor.toolbar.image': `Add image`,
  'wysiwygEditor.toolbar.table': `Add table`,
  'wysiwygEditor.toolbar.show_source': `Show HTML source`,
  'wysiwygEditor.toolbar.undo': `Undo`,
  'wysiwygEditor.toolbar.redo': `Redo`,
  'wysiwygEditor.toolbar.align_left': `Align left`,
  'wysiwygEditor.toolbar.align_center': `Align center`,
  'wysiwygEditor.toolbar.align_right': `Align right`,
  'wysiwygEditor.toolbar.align_justify': `Align justify`,
  'wysiwygEditor.toolbar.outdent': `Outdent`,
  'wysiwygEditor.toolbar.indent': `Indent`,
  'wysiwygEditor.toolbar.fullscreen': `Fullscreen`,

  'webhookCalls.event.item.create': `Record creation`,
  'webhookCalls.event.item.update': `Record update`,
  'webhookCalls.event.item.delete': `Record deletion`,
  'webhookCalls.event.item.publish': `Record publication`,
  'webhookCalls.event.item.unpublish': `Record marked as draft`,

  'webhookCalls.event.item_type.create': `Model creation`,
  'webhookCalls.event.item_type.update': `Model update`,
  'webhookCalls.event.item_type.delete': `Model deletion`,

  'webhookCalls.event.upload.create': `Asset creation`,
  'webhookCalls.event.upload.update': `Asset update`,
  'webhookCalls.event.upload.delete': `Asset deletion`,

  'webhookCalls.event.deployment_environment.deploy_started': `Deploy started`,
  'webhookCalls.event.deployment_environment.deploy_succeeded': `Deploy succeeded`,
  'webhookCalls.event.deployment_environment.deploy_failed': `Deploy failed`,

  'filter.placeholder.array': `Insert comma-separated {inputTypeName}s`,
  'filter.placeholder.single': `Insert a {inputTypeName}`,
  'filter.operator.eq': `is`,
  'filter.operator.neq': `is not`,
  'filter.operator.in': `is one of`,
  'filter.operator.not_in': `is not one of`,
  'filter.operator.exists': `exists`,
  'filter.operator.matches': `contains`,
  'filter.operator.not_matches': `doesn't contain`,
  'filter.operator.gt': `greater than`,
  'filter.date.operator.gt': `later than`,
  'filter.date.operator.gte': `later than or exactly`,
  'filter.date.operator.lt': `earlier than`,
  'filter.date.operator.lte': `earlier than or exactly`,
  'filter.date_time.operator.gt': `later than`,
  'filter.date_time.operator.gte': `later than or exactly`,
  'filter.date_time.operator.lt': `earlier than`,
  'filter.date_time.operator.lte': `earlier than or exactly`,
  'filter.operator.gte': `greater or equal`,
  'filter.operator.lt': `less than`,
  'filter.operator.lte': `less or equal`,
  'filter.operator.all_in': `contains all`,
  'filter.operator.any_in': `contains any of`,
  'filter.operator.near': `near`,
  'filter.label.pattern': `pattern`,
  'filter.label.case_sensitive': `case sensitive`,
  'filter.label.longitude': `longitude`,
  'filter.label.latitude': `latitude`,
  'filter.label.radius': `radius`,
  'filter.label.draft': `Draft`,
  'filter.label.published': `Published`,
  'filter.label.updated': `Updated`,
  'filter.boolean.label.true': `true`,
  'filter.boolean.label.false': `false`,
  'filter.label.true': `yes`,
  'filter.label.false': `no`,
  'filter.fieldType.string': `string`,
  'filter.fieldType.ID': `ID`,
  'filter.fieldType.item_id': `item id`,
  'filter.fieldType.upload_id': `ID`,
  'filter.fieldType.float': `float`,
  'filter.fieldType.integer': `integer`,
  'filter.fieldType.boolean': `boolean`,
  'filter.fieldType.date_time': `date and time`,
  'filter.fieldType.date': `date`,
  'filter.fieldType.enum': `status`,
  'filter.enum.placeholder': `Select one or more statuses`,
  'itemTable.columns.displayed': `Displayed columns`,
  'itemTable.columns.available': `Available columns`,
  'itemTable.id': `ID`,
  'itemTable.title': `Preview`,
  'itemTable.status': `Status`,
  'itemTable.updated_at': `Last update`,
  'itemTable.created_at': `Created at`,
  'itemTable.published_at': `Last published at`,
  'itemTable.first_published_at': `First published at`,
  'itemTable.publication_scheduled_at': `Scheduled publishing at`,
  'itemTable.editor': `Editor`,
  'itemTable.position': `Position`,
  'itemTable.creator': `Creator`,
  'itemTable.publishAtSpecificDate': `Publish at a specific date/time...`,
  'itemTable.insertRecords': `Add selected records`,
  'itemTable.show': `Show selected records`,
  'itemTable.hide': `Hide selected records`,
  'itemTable.records.count': `{count, plural, =0 {No records present} one {1 record} other {{count} records}}`,
  'itemTable.records.delete': `Delete`,
  'itemTable.records.publish': `Publish`,
  'itemTable.records.unpublish': `Unpublish`,
  'itemTable.records.deselect': `Deselect all`,
  'itemTable.records.selected': `{count, plural, one {One record selected} other {{count} records selected}}`,

  'admin.plugin.create.success': `Plugin installed successfully!`,
  'admin.plugin.create.failure': `Couldn't create plugin!`,
  'admin.plugin.update.success': `Plugin updated successfully!`,
  'admin.plugin.update.failure': `Couldn't update plugin!`,
  'admin.plugin.destroy.success': `Plugin deleted successfully!`,
  'admin.plugin.destroy.failure': `Couldn't delete plugin!`,

  'plugin.install': `Install plugin`,
  'plugin.pluginType': `Type of plugin`,
  'plugin.pluginType.hint': `DatoCMS supports different types of plugins. For more info, please read our <a href=\"https://www.datocms.com/docs/guides/building-plugins#types-of-plugins\">documentation</a>`,
  'pluginType.field_editor': `Field editor`,
  'pluginType.field_addon': `Field add-on`,
  'pluginType.sidebar': `Sidebar widget`,

  'newPlugin.fromUrl': `Install from URL`,
  'newPlugin.new': `Create new`,
  'newPlugin.library': `Community plugins`,
  'pluginLibrary.title': `DatoCMS Plugins`,
  'pluginLibrary.search.multiple.placeholder': `Search {total} plugins...`,
  'pluginLibrary.search.single.placeholder': `Find a plugin...`,
  'pluginLibrary.homepage': `Project homepage`,
  'pluginLibrary.install': `Install`,
  'pluginLibrary.installed': `Installed`,
  'pluginLibrary.installing': `Installing...`,
  'pluginLibrary.search': `Search`,
  'pluginLibrary.createMore': `Want to create more plugins?
  <a target="_blank" rel="noopener noreferrer" href="https://www.datocms.com/docs/guides/building-plugins" >
  Learn how to publish them </a> or just`,
  'pluginLibrary.createPrivate': `create a private one`,

  'form.editPlugin.uninstall': `Uninstall`,

  'plugins.noPlugins.title': `No plugins installed!`,
  'plugins.noPlugins.description': `Plugins add new features to your DatoCMS project. Install one of the plugins already made available by the community, or create one yourself!`,

  'itemTypeFilter.name': `Filter name`,
  'itemTypeFilter.sharingInfo': `Share this filter with every other user`,
  'itemTypeFilter.shared': `Shared filters`,
  'itemTypeFilter.personal': `Personal filters`,
  'itemTypeFilter.saved': `Saved Filters`,
  'itemTypeFilter.button.default': `Save filter`,
  'site.color.primary': `Primary color`,
  'site.color.accent': `Accent color`,
  'site.color.light': `Light color`,
  'site.color.dark': `Dark color`,
  'itemTypeFilter.create.success': `Filter created successfully!`,
  'itemTypeFilter.create.failure': `Couldn't create filter!`,
  'itemTypeFilter.update.success': `Filter updated successfully!`,
  'itemTypeFilter.update.failure': `Couldn't update filter!`,
  'itemTypeFilter.destroy.success': `Filter deleted successfully!`,
  'itemTypeFilter.destroy.failure': `Couldn't delete filter!`,

  'menuItem.externalUrl.hint': `http://www.example.com/`,
  'filter.add': `Add new filter`,
  'filter.edit': `Edit filter`,
  'filter.apply': `Apply`,
  'filter.search': `Search`,
  'filter.saveCurrent': `Save current search as filter...`,

  'form.schedulePublishing.date': `Publish this record at`,
  'form.schedulePublishing.button.default': `Set publication date`,

  'editor.item.changeCreator.success': `Creator changed successfully!`,
  'editor.item.changeCreator.failure': `Coudn't change creator!`,

  'accessToken.notEditable': `Non editable`,
  'accessToken.info': `This API token is present in every DatoCMS space and cannot be edited or deleted.`,
  'accessToken.apiKey': `API key`,
  'accessToken.canAccessCda': `Can access the Content Delivery API`,
  'accessToken.canAccessCda.hint': `GraphQL Endpoint: https://graphql.datocms.com/`,
  'accessToken.canAccessCdaPreview': `Can access the Content Delivery API with draft content`,
  'accessToken.canAccessCdaPreview.hint': `GraphQL Endpoint: https://graphql.datocms.com/preview`,
  'accessToken.canAccessCma': `Can access the Content Management API`,
  'accessToken.canAccessCma.hint': `REST Endpoint: https://site-api.datocms.com/*`,

  'seoInput.google': `Google search result`,
  'seoInput.twitter': `Twitter card`,
  'seoInput.facebook': `Facebook share`,
  'seoInput.configure': `Configure`,

  'size.small': `Small`,
  'size.normal': `Medium`,
  'size.large': `Large`,

  'limits.users.unlimited': `Unlimited collaborators`,
  'limits.users.none': `No collaborators invitable`,
  'limits.users.usage': `{unformattedValue, plural, one { invitable collaborator } other { {value} collaborators } }`,

  'limits.items.unlimited': `Unlimited records`,
  'limits.items.none': `No records`,
  'limits.items.usage': `{unformattedValue, plural, one { One record } other { {value} records } }`,

  'limits.item_types.unlimited': `Unlimited models`,
  'limits.item_types.none': `No models`,
  'limits.item_types.usage': `{unformattedValue, plural, one { One model } other { {value} models } }`,

  'limits.roles.unlimited': `Unlimited roles`,
  'limits.roles.none': `No roles`,
  'limits.roles.usage': `{unformattedValue, plural, one { One role } other { {value} roles } }`,

  'limits.deployment_environments.unlimited': `Unlimited environments`,
  'limits.deployment_environments.none': `No deployment environments`,
  'limits.deployment_environments.usage': `{unformattedValue, plural, one { One environment } other { {value} environments } }`,

  'limits.plugins.unlimited': `Unlimited plugins`,
  'limits.plugins.none': `No plugins`,
  'limits.plugins.usage': `{unformattedValue, plural, one { One plugin } other { {value} plugins } }`,

  'limits.title': `Project usage and plan limits`,
  'limits.dailyActivity': `Daily activity`,
  'limits.showChart': `Show chart as:`,
  'limits.cumulative': `Cumulative`,
  'limits.daily': `Daily`,
  'limits.apiTraffic': `Assets + GraphQL API traffic`,
  'limits.apiRequests': `API requests`,
  'limits.users': `Collaborators`,
  'limits.uploadable_bytes': `File storage`,
  'limits.plugins': `Plugins`,
  'limits.items': `Records`,
  'limits.traffic_bytes': `Traffic (per month)`,
  'limits.api_calls': `API calls (per month)`,
  'limits.custom_domain': `Custom domain`,
  'limits.access_tokens': `Custom API tokens`,
  'limits.otp': `Two-factor authentication`,
  'limits.version_history': `Revision history`,
  'limits.indexable_pages': `Indexable pages`,
  'limits.locales': `Locales`,
  'limits.item_types': `Models`,
  'limits.deployment_environments': `Deployment environments`,
  'limits.roles': `Roles`,

  'dailyUsage.cma_api_calls': `CMA API calls`,
  'dailyUsage.cda_api_calls': `CDA API calls`,
  'dailyUsage.cda_traffic_bytes': `CDA traffic`,
  'dailyUsage.assets_traffic_bytes': `Assets traffic`,

  'adminArea.siteSettings.title': `Project settings`,

  'headersInput.add': `Add new header`,
  'headersInput.key': `Header`,
  'headersInput.value': `Value`,

  'environmentVariablesInput.add': `Add new environment variable`,
  'environmentVariablesInput.key': `Env variable name`,
  'environmentVariablesInput.value': `Value`,

  'admin.users.title': `Collaborators`,

  'itemType.currentlyEditing': `{count, plural, one { {names} is } other { {names} are } } currently interacting with records of this model. Making changes to the schema might interfere with their work!`,
  'instructions.deployment': `<p>The job of building and deploying your static website is not performed directly by DatoCMS, but is delegated to an external Continuous Deployment service. <a target=\"_blank\" href=\"https://www.datocms.com/docs/general-concepts/deployment\">Read more in our docs</a>.</p>`,
  'instructions.pluginTypes.field_addon': `
    <p>Now that this field add-on is installed, you can use it in any of your <strong>{ fieldTypes }</strong> fields!</p>
    <p>In the <em>Presentation</em> tab of your field settings, you'll be able to add (and configure) this add-on:</p>
    <p><img class="with-zoom" src="/assets/images/plugins/field_addon.gif" /></p>
  `,
  'instructions.pluginTypes.field_editor': `
    <p>Now that this field editor is installed, you can use it in any of your <strong>{ fieldTypes }</strong> fields!</p>
    <p>In the <em>Presentation</em> tab of your field settings, you'll be able choose this plugin as the field editor, and configure its settings:</p>
    <p><img class="with-zoom" src="/assets/images/plugins/field_editor.gif" /></p>
  `,
  'instructions.pluginTypes.sidebar': `
    <p>Now that this sidebar widget is installed, you can add it to in any of your model!</p>
    <p>In one of your models create a new <strong>{ orFieldTypes }</strong> field, and in the <em>Presentation</em> tab choose this plugin as its field editor:</p>
    <p><img class="with-zoom" src="/assets/images/plugins/sidebar.gif" /></p>
  `,
  'instructions.logs': `
    <p>Here you can monitor in real-time the <strong>status of the communication between DatoCMS and your Continuous Deployment</strong>.</p>
    <p>If something goes wrong during the publishing process, this is the first place to look for hints.</p>
  `,
  'instructions.plugins': `
    <p>Plugins allow developers to extend the basic functionality of the DatoCMS administrative area. You, the developer, are in charge of writing and hosting the plugin.</p>
    <p>Technically speaking Plugins are small HTML5 applications that exist in a sandboxed <code>&#x3C;iframe></code> and interact with the main DatoCMS webapp through a JS library you need to include — <a href="https://www.datocms.com/docs/guides/building-plugins/sdk-reference">the Plugins SDK</a>.</p>
    <p>You can write them with basic HTML and JavaScript, or using more advanced client-side frameworks such as React, Angular or Vue.</p>
    <p>Want to know more? Read how to install, develop and share plugins to the community in <a target="_blank" href="https://www.datocms.com/docs/guides/building-plugins">our guide</a>!</p>
  `,
  'messages.confirm.takeOver.title': `Take over this record?`,
  'messages.confirm.takeOver.question': `If you proceed, { user } will be kicked out from his editing session, and you will be able to make changes to this record instead.`,
  'messages.confirm.takeOver.ok': `Yes, take control of this record`,
  'messages.confirm.takeOver.cancel': `Cancel`,
  'messages.dataRecovered': `Data has been successfully recovered!`,
  'messages.takenOver': `Record has been successfully taken over!`,

  'validator.required_seo_fields.title': `Required`,
  'validator.required_seo_fields.hint': `Specify which meta information has to be present`,

  'fullTextQuery.placeholder': `Search...`,
  'event.record': `Record`,
  'event.model': `Model`,
  'event.upload': `Upload`,
  'event.deploymentEnvironment': `Deployment environment`,
  'event.model.noFilter': `No filter — this webhook will trigger for any model`,
  'event.model.only': `Trigger only on specific models`,
  'event.record.noFilter': `No filter — this webhook will trigger for any record`,
  'event.record.only': `Trigger only on specific records`,
  'event.record.modelOnly': `Trigger only on records of specific models`,
  'event.deploymentEnvironment.noFilter': `'No filter — this webhook will trigger for any environment'`,
  'event.deploymentEnvironment.only': `Trigger only on specific environments`,
  'event.publish': `Publish`,
  'event.unpublish': `Unpublish`,
  'event.create': `Create`,
  'event.update': `Update`,
  'event.delete': `Delete`,
  'event.deployStarted': `Deploy started`,
  'event.deploySucceeded': `Deploy succeeded`,
  'event.deployFailed': `Deploy failed`,
  'netlifySettings.noLink': `This site is currently linked to this Netlify project:`,
  'netlifySettings.changeLink': `Want to link to a different Netlify project?`,
  'netlifySettings.noProjects': `The Netlify account you selected does not have any project!`,
  'netlifySettings.loadingProjects': `Loading your Netlify projects...`,
  'netlifySettings.createProject': `Create a new Netlify project`,
  'netlifySettings.projectCreated': `I&apos;ve created a new project, refresh the list`,
  'netlifySettings.projectSelect': `Select the Netlify project to link to this DatoCMS backend:`,
  'netlifySettings.integrationStart': `Click the button to sign in to your Netlify account and start the integration!`,
  'netlifySettings.hooks.creation': `Setting up deployment hooks...`,
  'netlifySettings.hooks.success': `Creating success hook...`,
  'netlifySettings.hooks.failure': `Creating failure hook...`,
  'netlifySettings.hooks.build': `Creating build hook...`,
  'netlifySettings.hooks.done': `done!`,
  'itemLocking.disabled': `Record editing is disabled!`,
  'itemLocking.takeOver': `Take over`,
  'itemLocking.recoverFrom': `Recover the work started by`,
  'itemLocking.recover': `Recover`,
  'itemLocking.getOtherUserData1': `You now have control over this record. Would you like to recover `,
  'itemLocking.getOtherUserData2': `&rsquo;s unsaved changes?`,
  'itemLocking.locked': `You are currently editing this record from another tab: you cannot make changes, unless you take over from here.`,
  'itemLocking.currentlyEditing': `is currently working on this record, which means you cannot make changes, unless you take over.`,
  'recordInfo.title': `Record info`,
  'recordInfo.createdBy': `Created by`,
  'recordInfo.createdAt': `Created at`,
  'recordInfo.firstPublished': `First published at`,
  'recordInfo.lastUpdate': `Last update`,
  'recordInfo.lastPublished': `Last published`,
  'recordInfo.nextPublication': `Next publication`,
  'sidebar.revisionHistory': `Revision history`,
  'sidebar.actions': `Actions`,
  'gallery.noImage': `No image available.`,
  'gallery.noFile': `No file available.`,
  'gallery.noFiles': `No files present`,
  'item.saving': `Saving...`,
  'item.save': `Save`,
  'item.back': `Back`,
  'localesInput.switch': `Switch to...`,
  'localesInput.add': `Add new locale...`,
  'versions.title': `Record history`,
  'versions.restore.title': `Restore this version?`,
  'versions.restore.description': `You're viewing the revision {user} made {date}.`,
  'versions.restore.action': `Restore this revision`,
  'versions.restore.disabled': `You cannot rollback right now as someone is editing this record`,
};
